# Generated by Django 5.2.17 on 2026-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='lyric',
            field=models.TextField(blank=True, verbose_name='歌词'),
        ),
    ]
